### ISSUE TITLE
Segfault

### ISSUE THREAD

**Issue by mateuszgwozdz** [KSIUJ/ksicamp-the-game#6]
Przy wypisywaniu co mamy w kieszeniach po śmierci

**Comment by phoe** [comment]
Kto zepsuł mastera? :stuck_out_tongue: 

```
┌─[phoe][phoetower][±][master ✓][~/Projects/Git/ksicamp-the-game]
└─▪ g++ --std=c++11 -g -Wall -fsanitize=undefined -fsanitize=address -D_GLIBCXX_DEBUG -o ksicamp-the-game main.cpp util.cpp rooms/*.cpp
┌─[phoe][phoetower][±][master ✓][~/Projects/Git/ksicamp-the-game]
└─▪ ./ksicamp-the-game 

        **** KSICAMP - THE GAME ****
        designed by the KSICAMP team

Obudziłeś się.
main.hpp:53:29: runtime error: index 10 out of bounds for type '<unknown> *[9]'
Jesteś w KSI. Słońce zaszło dawno temu. Coś musiało pójść bardzo nie tak.
Obok ciebie leżą kawałki niedojedzonej pizzy. 
Bierzesz jeden?
nie
Wychodzisz na korytarz przed KSI.

Idziesz przez korytarz. Spotykasz Dziekana.
Uciekasz przed nim?
nie
Mówisz, "Dzień dobry, panie Dziekanie" i przechodzisz koło niego.
Dokąd dalej?
1) Serweronia
2) WC
3) Winda
4) KSI
1
Idziesz w stronę 1

Ten pokój nie istnieje. Spadłeś w pustkę. Elo.

Koniec gry.
Wynik: Przegrałeś.
W kieszeniach masz:
* nic
AddressSanitizer:DEADLYSIGNAL
=================================================================
==9320==ERROR: AddressSanitizer: SEGV on unknown address 0x560416169c1e (pc 0x7ff2e3494870 bp 0x7ffcab916700 sp 0x7ffcab916548 T0)
==9320==The signal is caused by a WRITE memory access.
    #0 0x7ff2e349486f  (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb886f)
    #1 0x7ff2e34948d8 in __gnu_debug::_Safe_sequence_base::_M_detach_all() (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb88d8)
    #2 0x560416163038 in __gnu_debug::_Safe_sequence_base::~_Safe_sequence_base() /usr/include/c++/8/debug/safe_base.h:221
    #3 0x560416163129 in __gnu_debug::_Safe_sequence<std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::~_Safe_sequence() (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x50129)
    #4 0x56041616321f in __gnu_debug::_Safe_node_sequence<std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >::~_Safe_node_sequence() (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x5021f)
    #5 0x560416163315 in __gnu_debug::_Safe_container<std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_debug::_Safe_node_sequence, true>::~_Safe_container() (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x50315)
    #6 0x5604161636b1 in std::__debug::set<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >::~set() (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x506b1)
    #7 0x560416163e88 in GameData::~GameData() (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x50e88)
    #8 0x560416161a76 in main /home/phoe/Projects/Git/ksicamp-the-game/main.cpp:29
    #9 0x7ff2e2572b16 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x22b16)
    #10 0x560416160569 in _start (/home/phoe/Projects/Git/ksicamp-the-game/ksicamp-the-game+0x4d569)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/usr/lib/x86_64-linux-gnu/libstdc++.so.6+0xb886f) 
==9320==ABORTING
```

**Comment by mateuszgwozdz** [comment]
nie ja ;____________;
po moim działało

**Comment by phoe** [comment]
Sprawdzę jutro.

**Comment by polarny** [comment]
To chyba moja wina, ale mam na to fix, właśnie przetestowałem i u mnie działa.
Ściągnij teraz i sprawdź czy działa.

**Comment by phoe** [comment]
Dzięki za poprawkę.

Zgodnie z zasadami, projekt się buduje i kompilator nie sypie błędami. Błąd jest w runtime, więc karniaka nie ma.
